### ISSUE TITLE
Importing get_data from nlpia.loaders causes Error with python 3.10.2 

### ISSUE THREAD

**Issue by conradfriedrich** [totalgood/nlpia#46]
```from nlpia.loaders import get_data ```

causes 

```
Traceback (most recent call last):
  File "xyz.py", line 2, in <module>
    from nlpia.loaders import get_data
  File ".venv/lib/python3.10/site-packages/nlpia/loaders.py", line 61, in <module>
    from pugnlp.util import clean_columns
  File ".venv/lib/python3.10/site-packages/pugnlp/util.py", line 47, in <module>
    from collections import OrderedDict, Mapping, Counter
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

on Manjaro Linux 4.19.233-1
python version 3.10.2

**Comment by conradfriedrich** [comment]
replacing 

```
from collections import Mapping
```
with 
``` 
from collections.abc import Mapping
```

as per [stackoverflow issue](https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections) wherever `Mapping` is imported (see below) seems to successfully address the issue. Note that `OrderedDict, Counter` still have to be imported from `collections`, not `collections.abc`

pugnlp/util.py, line 47                                       
pugnlp/constants.py, line 16
pugnlp/futil.py, line 17
